use_frameworks!

platform :ios, '9.0'

target 'SWHelloWorld_Example' do
  pod 'SWHelloWorld', :path => '../'

  target 'SWHelloWorld_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
